### ISSUE TITLE
Typo in the second heading of Views.astro

### ISSUE THREAD

**Issue by eanorambuena** [JSConfCL/2024_web#1]
There is a typo in the second h3 of Views.astro. It should be 'previa' instead of 'precia'.

![image](https://github.com/user-attachments/assets/1c687015-4f42-440b-9c24-c49ea597cf83)

**Comment by odracirdev** [comment]
Hola @eanorambuena el typo fue arreglado en su momento pero no había visto la issue. Perdón por no responder a tiempo 🥹
